---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
## Load the data
activity<-read.csv("activity.csv",sep=",")
```

## What is mean total number of steps taken per day?

```{r}
## Calculate the total number of steps taken per day
totalsteps<-lapply(split(activity$steps,activity$date),function(x) sum(x,na.rm=TRUE))
totalsteps<-unlist(totalsteps)
## Make a histogram of the total number of steps taken each day
hist(totalsteps,main="total number of steps taken each day")
## Calculate and report the mean and median of the total number of steps taken per day
summary(totalsteps)
```

## What is the average daily activity pattern?

```{r}
averagesteps<-lapply(split(activity$steps,activity$interval),function(x) mean(x,na.rm=TRUE))
averagesteps<-unlist(averagesteps)
averagestepsinterval<-cbind(interval=unique(activity$interval),averagesteps)
## Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, 
## averaged across all days (y-axis)
plot(averagestepsinterval[,1],averagestepsinterval[,2],type="l",xlab="5-minute interval",
ylab="average number of steps across all days")
## Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
summary(averagesteps)
averagestepsinterval[averagestepsinterval[,2]==max(averagesteps),]
```

## Imputing missing values

```{r}
## Calculate and report the total number of missing values in the dataset 
table(is.na(activity$steps))
## Devise a strategy for filling in all of the missing values in the dataset
## (using  the mean for that 5-minute interval)
activity2<-cbind(activity,averagesteps)
## Create a new dataset that is equal to the original dataset but with the missing data filled in
for(i in 1:nrow(activity2))
  if (is.na(activity2[i,1]))
    activity2[i,1]<-activity2[i,4]
totalsteps2<-lapply(split(activity2$steps,activity2$date),function(x) sum(x,na.rm=TRUE))
totalsteps2<-unlist(totalsteps2)
## Make a histogram of the total number of steps taken each day
hist(totalsteps2,main="total number of steps taken each day")
## Calculate and report the mean and median total number of steps taken per day
summary(totalsteps)
summary(totalsteps2)
```

## Are there differences in activity patterns between weekdays and weekends?
